services:
  dnkelly:
    build:
       context: ./dnkelly/
    command: gunicorn dnkelly.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./dnkelly/:/usr/src/dnkelly/
      - static_files_dnkelly:/usr/src/dnkelly/staticfiles
    expose:
      - 8000
      # ports:
      # - 8000:8000
    env_file:
      - ./dnkelly/.env

  universityofmars:
    build:
       context: ./universityofmars/
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn universityofmars.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./universityofmars/:/usr/src/universityofmars/
      - static_files_universityofmars:/usr/src/universityofmars/staticfiles
    expose:
      - 8080
      # ports:
      # - 8000:8000
    env_file:
      - ./universityofmars/.env

  nginx:
    build:
       context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/templates/:/etc/nginx/templates
      - static_files_dnkelly:/home/dnkelly/staticfiles
      - static_files_universityofmars:/home/universityofmars/staticfiles
    env_file:
      - ./.env/dev.env

  dns:
    build:
      context: ./dns/
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zone/:/etc/bind/zone/
    command: named -c /etc/bind/named.conf -g -u named

volumes:
  static_files_dnkelly:
  static_files_universityofmars:
